const areaCodes = [
    { name: "El Salvador", code: "+503", flag: "🇸🇻" },
    { name: "Guatemala", code: "+502", flag: "🇬🇹" },
    { name: "Honduras", code: "+504", flag: "🇭🇳" },
    { name: "Nicaragua", code: "+505", flag: "🇳🇮" },
    { name: "Costa Rica", code: "+506", flag: "🇨🇷" },
    { name: "Panamá", code: "+507", flag: "🇵🇦" },
    { name: "México", code: "+52", flag: "🇲🇽" },
    { name: "Estados Unidos", code: "+1", flag: "🇺🇸" },
    { name: "Canadá", code: "+1", flag: "🇨🇦" },
    { name: "Afganistán", code: "+93", flag: "🇦🇫" },
    { name: "Albania", code: "+355", flag: "🇦🇱" },
    { name: "Alemania", code: "+49", flag: "🇩🇪" },
    { name: "Andorra", code: "+376", flag: "🇦🇩" },
    { name: "Angola", code: "+244", flag: "🇦🇴" },
    { name: "Arabia Saudita", code: "+966", flag: "🇸🇦" },
    { name: "Argelia", code: "+213", flag: "🇩🇿" },
    { name: "Argentina", code: "+54", flag: "🇦🇷" },
    { name: "Armenia", code: "+374", flag: "🇦🇲" },
    { name: "Australia", code: "+61", flag: "🇦🇺" },
    { name: "Austria", code: "+43", flag: "🇦🇹" },
    { name: "Azerbaiyán", code: "+994", flag: "🇦🇿" },
    { name: "Bahamas", code: "+1-242", flag: "🇧🇸" },
    { name: "Bangladés", code: "+880", flag: "🇧🇩" },
    { name: "Barbados", code: "+1-246", flag: "🇧🇧" },
    { name: "Baréin", code: "+973", flag: "🇧🇭" },
    { name: "Bélgica", code: "+32", flag: "🇧🇪" },
    { name: "Belice", code: "+501", flag: "🇧🇿" },
    { name: "Benín", code: "+229", flag: "🇧🇯" },
    { name: "Bielorrusia", code: "+375", flag: "🇧🇾" },
    { name: "Birmania", code: "+95", flag: "🇲🇲" },
    { name: "Bolivia", code: "+591", flag: "🇧🇴" },
    { name: "Bosnia y Herzegovina", code: "+387", flag: "🇧🇦" },
    { name: "Botsuana", code: "+267", flag: "🇧🇼" },
    { name: "Brasil", code: "+55", flag: "🇧🇷" },
    { name: "Brunéi", code: "+673", flag: "🇧🇳" },
    { name: "Bulgaria", code: "+359", flag: "🇧🇬" },
    { name: "Burkina Faso", code: "+226", flag: "🇧🇫" },
    { name: "Burundi", code: "+257", flag: "🇧🇮" },
    { name: "Bután", code: "+975", flag: "🇧🇹" },
    { name: "Cabo Verde", code: "+238", flag: "🇨🇻" },
    { name: "Camboya", code: "+855", flag: "🇰🇭" },
    { name: "Camerún", code: "+237", flag: "🇨🇲" },
    { name: "Catar", code: "+974", flag: "🇶🇦" },
    { name: "Chad", code: "+235", flag: "🇹🇩" },
    { name: "Chile", code: "+56", flag: "🇨🇱" },
    { name: "China", code: "+86", flag: "🇨🇳" },
    { name: "Chipre", code: "+357", flag: "🇨🇾" },
    { name: "Colombia", code: "+57", flag: "🇨🇴" },
    { name: "Comoras", code: "+269", flag: "🇰🇲" },
    { name: "Corea del Norte", code: "+850", flag: "🇰🇵" },
    { name: "Corea del Sur", code: "+82", flag: "🇰🇷" },
    { name: "Costa de Marfil", code: "+225", flag: "🇨🇮" },
    { name: "Croacia", code: "+385", flag: "🇭🇷" },
    { name: "Cuba", code: "+53", flag: "🇨🇺" },
    { name: "Dinamarca", code: "+45", flag: "🇩🇰" },
    { name: "Dominica", code: "+1-767", flag: "🇩🇲" },
    { name: "Ecuador", code: "+593", flag: "🇪🇨" },
    { name: "Egipto", code: "+20", flag: "🇪🇬" },
    { name: "Emiratos Árabes Unidos", code: "+971", flag: "🇦🇪" },
    { name: "Eritrea", code: "+291", flag: "🇪🇷" },
    { name: "Eslovaquia", code: "+421", flag: "🇸🇰" },
    { name: "Eslovenia", code: "+386", flag: "🇸🇮" },
    { name: "España", code: "+34", flag: "🇪🇸" },
    { name: "Estonia", code: "+372", flag: "🇪🇪" },
    { name: "Etiopía", code: "+251", flag: "🇪🇹" },
    { name: "Filipinas", code: "+63", flag: "🇵🇭" },
    { name: "Finlandia", code: "+358", flag: "🇫🇮" },
    { name: "Fiyi", code: "+679", flag: "🇫🇯" },
    { name: "Francia", code: "+33", flag: "🇫🇷" },
    { name: "Gabón", code: "+241", flag: "🇬🇦" },
    { name: "Gambia", code: "+220", flag: "🇬🇲" },
    { name: "Georgia", code: "+995", flag: "🇬🇪" },
    { name: "Ghana", code: "+233", flag: "🇬🇭" },
    { name: "Granada", code: "+1-473", flag: "🇬🇩" },
    { name: "Grecia", code: "+30", flag: "🇬🇷" },
    { name: "Guinea", code: "+224", flag: "🇬🇳" },
    { name: "Guinea-Bisáu", code: "+245", flag: "🇬🇼" },
    { name: "Guinea Ecuatorial", code: "+240", flag: "🇬🇶" },
    { name: "Guyana", code: "+592", flag: "🇬🇾" },
    { name: "Haití", code: "+509", flag: "🇭🇹" },
    { name: "Hungría", code: "+36", flag: "🇭🇺" },
    { name: "India", code: "+91", flag: "🇮🇳" },
    { name: "Indonesia", code: "+62", flag: "🇮🇩" },
    { name: "Irak", code: "+964", flag: "🇮🇶" },
    { name: "Irán", code: "+98", flag: "🇮🇷" },
    { name: "Irlanda", code: "+353", flag: "🇮🇪" },
    { name: "Islandia", code: "+354", flag: "🇮🇸" },
    { name: "Islas Marshall", code: "+692", flag: "🇲🇭" },
    { name: "Islas Salomón", code: "+677", flag: "🇸🇧" },
    { name: "Israel", code: "+972", flag: "🇮🇱" },
    { name: "Italia", code: "+39", flag: "🇮🇹" },
    { name: "Jamaica", code: "+1-876", flag: "🇯🇲" },
    { name: "Japón", code: "+81", flag: "🇯🇵" },
    { name: "Jordania", code: "+962", flag: "🇯🇴" },
    { name: "Kazajistán", code: "+7", flag: "🇰🇿" },
    { name: "Kenia", code: "+254", flag: "🇰🇪" },
    { name: "Kirguistán", code: "+996", flag: "🇰🇬" },
    { name: "Kiribati", code: "+686", flag: "🇰🇮" },
    { name: "Kuwait", code: "+965", flag: "🇰🇼" },
    { name: "Laos", code: "+856", flag: "🇱🇦" },
    { name: "Lesoto", code: "+266", flag: "🇱🇸" },
    { name: "Letonia", code: "+371", flag: "🇱🇻" },
    { name: "Líbano", code: "+961", flag: "🇱🇧" },
    { name: "Liberia", code: "+231", flag: "🇱🇷" },
    { name: "Libia", code: "+218", flag: "🇱🇾" },
    { name: "Liechtenstein", code: "+423", flag: "🇱🇮" },
    { name: "Lituania", code: "+370", flag: "🇱🇹" },
    { name: "Luxemburgo", code: "+352", flag: "🇱🇺" },
    { name: "Macedonia del Norte", code: "+389", flag: "🇲🇰" },
    { name: "Madagascar", code: "+261", flag: "🇲🇬" },
    { name: "Malasia", code: "+60", flag: "🇲🇾" },
    { name: "Malaui", code: "+265", flag: "🇲🇼" },
    { name: "Maldivas", code: "+960", flag: "🇲🇻" },
    { name: "Malí", code: "+223", flag: "🇲🇱" },
    { name: "Malta", code: "+356", flag: "🇲🇹" },
    { name: "Marruecos", code: "+212", flag: "🇲🇦" },
    { name: "Mauricio", code: "+230", flag: "🇲🇺" },
    { name: "Mauritania", code: "+222", flag: "🇲🇷" },
    { name: "Micronesia", code: "+691", flag: "🇫🇲" },
    { name: "Moldavia", code: "+373", flag: "🇲🇩" },
    { name: "Mónaco", code: "+377", flag: "🇲🇨" },
    { name: "Mongolia", code: "+976", flag: "🇲🇳" },
    { name: "Montenegro", code: "+382", flag: "🇲🇪" },
    { name: "Mozambique", code: "+258", flag: "🇲🇿" },
    { name: "Namibia", code: "+264", flag: "🇳🇦" },
    { name: "Nauru", code: "+674", flag: "🇳🇷" },
    { name: "Nepal", code: "+977", flag: "🇳🇵" },
    { name: "Níger", code: "+227", flag: "🇳🇪" },
    { name: "Nigeria", code: "+234", flag: "🇳🇬" },
    { name: "Noruega", code: "+47", flag: "🇳🇴" },
    { name: "Nueva Zelanda", code: "+64", flag: "🇳🇿" },
    { name: "Omán", code: "+968", flag: "🇴🇲" },
    { name: "Países Bajos", code: "+31", flag: "🇳🇱" },
    { name: "Pakistán", code: "+92", flag: "🇵🇰" },
    { name: "Palaos", code: "+680", flag: "🇵🇼" },
    { name: "Palestina", code: "+970", flag: "🇵🇸" },
    { name: "Papúa Nueva Guinea", code: "+675", flag: "🇵🇬" },
    { name: "Paraguay", code: "+595", flag: "🇵🇾" },
    { name: "Perú", code: "+51", flag: "🇵🇪" },
    { name: "Polonia", code: "+48", flag: "🇵🇱" },
    { name: "Portugal", code: "+351", flag: "🇵🇹" },
    { name: "Puerto Rico", code: "+1-787", flag: "🇵🇷" },
    { name: "Reino Unido", code: "+44", flag: "🇬🇧" },
    { name: "República Centroafricana", code: "+236", flag: "🇨🇫" },
    { name: "República Checa", code: "+420", flag: "🇨🇿" },
    { name: "República del Congo", code: "+242", flag: "🇨🇬" },
    { name: "República Democrática del Congo", code: "+243", flag: "🇨🇩" },
    { name: "República Dominicana", code: "+1-809", flag: "🇩🇴" },
    { name: "Ruanda", code: "+250", flag: "🇷🇼" },
    { name: "Rumania", code: "+40", flag: "🇷🇴" },
    { name: "Rusia", code: "+7", flag: "🇷🇺" },
    { name: "Samoa", code: "+685", flag: "🇼🇸" },
    { name: "San Cristóbal y Nieves", code: "+1-869", flag: "🇰🇳" },
    { name: "San Marino", code: "+378", flag: "🇸🇲" },
    { name: "San Vicente y las Granadinas", code: "+1-784", flag: "🇻🇨" },
    { name: "Santa Lucía", code: "+1-758", flag: "🇱🇨" },
    { name: "Santo Tomé y Príncipe", code: "+239", flag: "🇸🇹" },
    { name: "Senegal", code: "+221", flag: "🇸🇳" },
    { name: "Serbia", code: "+381", flag: "🇷🇸" },
    { name: "Seychelles", code: "+248", flag: "🇸🇨" },
    { name: "Sierra Leona", code: "+232", flag: "🇸🇱" },
    { name: "Singapur", code: "+65", flag: "🇸🇬" },
    { name: "Siria", code: "+963", flag: "🇸🇾" },
    { name: "Somalia", code: "+252", flag: "🇸🇴" },
    { name: "Sri Lanka", code: "+94", flag: "🇱🇰" },
    { name: "Suazilandia", code: "+268", flag: "🇸🇿" },
    { name: "Sudáfrica", code: "+27", flag: "🇿🇦" },
    { name: "Sudán", code: "+249", flag: "🇸🇩" },
    { name: "Sudán del Sur", code: "+211", flag: "🇸🇸" },
    { name: "Suecia", code: "+46", flag: "🇸🇪" },
    { name: "Suiza", code: "+41", flag: "🇨🇭" },
    { name: "Surinam", code: "+597", flag: "🇸🇷" },
    { name: "Tailandia", code: "+66", flag: "🇹🇭" },
    { name: "Tanzania", code: "+255", flag: "🇹🇿" },
    { name: "Tayikistán", code: "+992", flag: "🇹🇯" },
    { name: "Timor Oriental", code: "+670", flag: "🇹🇱" },
    { name: "Togo", code: "+228", flag: "🇹🇬" },
    { name: "Tonga", code: "+676", flag: "🇹🇴" },
    { name: "Trinidad y Tobago", code: "+1-868", flag: "🇹🇹" },
    { name: "Túnez", code: "+216", flag: "🇹🇳" },
    { name: "Turkmenistán", code: "+993", flag: "🇹🇲" },
    { name: "Turquía", code: "+90", flag: "🇹🇷" },
    { name: "Tuvalu", code: "+688", flag: "🇹🇻" },
    { name: "Ucrania", code: "+380", flag: "🇺🇦" },
    { name: "Uganda", code: "+256", flag: "🇺🇬" },
    { name: "Uruguay", code: "+598", flag: "🇺🇾" },
    { name: "Uzbekistán", code: "+998", flag: "🇺🇿" },
    { name: "Vanuatu", code: "+678", flag: "🇻🇺" },
    { name: "Venezuela", code: "+58", flag: "🇻🇪" },
    { name: "Vietnam", code: "+84", flag: "🇻🇳" },
    { name: "Yemen", code: "+967", flag: "🇾🇪" },
    { name: "Yibuti", code: "+253", flag: "🇩🇯" },
    { name: "Zambia", code: "+260", flag: "🇿🇲" },
    { name: "Zimbabue", code: "+263", flag: "🇿🇼" },
];

document.addEventListener('DOMContentLoaded', function () {
    const areaSelects = document.querySelectorAll(".area2");

    if (areaSelects.length > 0) {
        areaCodes.sort((a, b) => a.name.localeCompare(b.name));

        areaSelects.forEach(areaSelect => {
            if (areaSelect) {
                areaSelect.innerHTML = '<option value="" disabled selected></option>';

                areaCodes.forEach(country => {
                    const option = document.createElement('option');
                    option.value = country.code;
                    option.textContent = `${country.flag} ${country.code}`;
                    areaSelect.appendChild(option);
                });

                const defaultCountry = areaCodes.find(c => c.name === "El Salvador");
                if (defaultCountry) {
                    areaSelect.value = defaultCountry.code;
                }
            }
        });
    }
});
